export enum QUERY_KEY_ENUM {
  PROFILE = 'profile',
  CATEGORY = 'list-category',
  MORE_CATEGORY = 'more-category',
  CATEGORY_LIST = 'category',
  PRODUCT = 'product',
  PRODUCT_ADDON = 'product-addon',
  PRODUCT_ADDON_DETAIL = 'product-addon-detail',
  PRODUCT_ADDON_ITEM = 'product-addon-item',
  ORDER = 'order-list',
  ADDRESS_LIST = 'address-list',
  ADDRESS_CREATE = 'address-create',
  EQUIPMENT = 'equipment',
  BANNER = 'list-banner',
  BANNER_DETAIL = 'banner-detail',
  ORDER_SUMMARY = 'order-summary',
  NOTE = 'homepage',
  SCHEDULE = 'order-available-schedule',
  EDIT_SCHEDULE = 'order-bulk-edit-schedule'
}
