/**
 * longcelot-sheet-db → Production DB Data Export Script
 * Generated by: sheet-db export-data
 * Exports admin sheet data only
 *
 * Steps:
 *   1. Install your production DB adapter (e.g. @prisma/client)
 *   2. Replace the stub insertRow() with your real DB write
 *   3. Run: node export-data.js
 */

const { createSheetAdapter } = require('longcelot-sheet-db');
require('dotenv').config();

// Schemas embedded at generation time (pattern validators omitted — read-only export)
const schemas = [
  {"name":"categories","actor":"admin","timestamps":true,"softDelete":true,"columns":{"name_en":{"type":"string","required":true},"name_km":{"type":"string","required":true},"thumbnail_url":{"type":"string"},"status":{"type":"boolean","default":true},"sort":{"type":"number","default":0},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_deleted_at":{"type":"date"},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"category_addon_items","actor":"admin","timestamps":true,"softDelete":true,"columns":{"addon_id":{"type":"string","required":true,"ref":"category_addons._id"},"name_en":{"type":"string","required":true},"name_km":{"type":"string","required":true},"type":{"type":"string","required":true},"img_url":{"type":"string"},"amount":{"type":"number","min":0,"default":0},"duration":{"type":"number","min":0,"default":0},"status":{"type":"boolean","default":true},"sort":{"type":"number","default":0},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_deleted_at":{"type":"date"},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"category_addons","actor":"admin","timestamps":true,"softDelete":true,"columns":{"name_en":{"type":"string","required":true},"name_km":{"type":"string","required":true},"badge_en":{"type":"string"},"badge_km":{"type":"string"},"selection_type":{"type":"string","enum":["SINGLE","MULTIPLE"],"default":"SINGLE"},"is_required":{"type":"boolean","default":false},"status":{"type":"boolean","default":true},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_deleted_at":{"type":"date"},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"category_category_addons","actor":"admin","timestamps":true,"columns":{"category_id":{"type":"string","required":true,"ref":"categories._id"},"addon_id":{"type":"string","required":true,"ref":"category_addons._id"},"sort":{"type":"number","default":0},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"category_products","actor":"admin","timestamps":true,"columns":{"category_id":{"type":"string","required":true,"ref":"categories._id"},"product_id":{"type":"string","required":true,"ref":"products._id"},"sort":{"type":"number","default":0},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"credentials","actor":"admin","columns":{"user_id":{"type":"string","required":true},"password_hash":{"type":"string"},"provider":{"type":"string","enum":["oauth","local"],"required":true},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"items","actor":"admin","timestamps":true,"softDelete":true,"columns":{"name_en":{"type":"string","required":true},"name_km":{"type":"string","required":true},"category":{"type":"string","required":true},"status":{"type":"boolean","default":true},"sort_order":{"type":"number","default":0},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_deleted_at":{"type":"date"},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"permissions","actor":"admin","timestamps":true,"columns":{"module":{"type":"string","required":true},"action":{"type":"string","required":true,"enum":["VIEW","ADD","UPDATE","DELETE","EXPORT","ASSIGN","MARK_AS_PAID"]},"description":{"type":"string"},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"popular_service_items","actor":"admin","timestamps":true,"columns":{"popular_service_id":{"type":"string","required":true,"ref":"popular_services._id"},"type":{"type":"string","required":true,"enum":["CATEGORY","PRODUCT"]},"category_id":{"type":"string","ref":"categories._id"},"product_id":{"type":"string","ref":"products._id"},"priority":{"type":"number","default":0},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"popular_services","actor":"admin","timestamps":true,"softDelete":true,"columns":{"name_en":{"type":"string","required":true},"name_km":{"type":"string","required":true},"image_url":{"type":"string"},"status":{"type":"boolean","default":true},"display_order":{"type":"number","default":0},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_deleted_at":{"type":"date"},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"product_options","actor":"admin","timestamps":true,"softDelete":true,"columns":{"product_id":{"type":"string","required":true,"ref":"products._id"},"name_en":{"type":"string","required":true},"name_km":{"type":"string","required":true},"type":{"type":"string","required":true},"amount":{"type":"number","min":0,"default":0},"status":{"type":"boolean","default":true},"sort":{"type":"number","default":0},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_deleted_at":{"type":"date"},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"products","actor":"admin","timestamps":true,"softDelete":true,"columns":{"name_en":{"type":"string","required":true},"name_km":{"type":"string","required":true},"base_price":{"type":"number","min":0,"required":true},"duration":{"type":"number","min":0,"required":true},"status":{"type":"boolean","default":true},"sort":{"type":"number","default":0},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_deleted_at":{"type":"date"},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"role_permissions","actor":"admin","timestamps":true,"columns":{"role_id":{"type":"string","required":true},"module":{"type":"string","required":true},"action":{"type":"string","required":true},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"roles","actor":"admin","timestamps":true,"softDelete":true,"columns":{"name":{"type":"string","required":true,"unique":true},"code":{"type":"string","required":true,"unique":true},"description":{"type":"string"},"status":{"type":"string","enum":["active","inactive"],"default":"active"},"created_by":{"type":"string","required":true},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_deleted_at":{"type":"date"},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"schema_versions","actor":"admin","pkColumn":"schema_version_id","columns":{"schema_version_id":{"type":"string","primary":true,"unique":true,"required":true},"actor_sheet_id":{"type":"string","required":true},"table_name":{"type":"string","required":true},"schema_hash":{"type":"string","required":true},"synced_at":{"type":"string","required":true},"column_count":{"type":"number","required":true},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"task_info","actor":"admin","timestamps":true,"softDelete":true,"columns":{"category_id":{"type":"string","ref":"categories._id"},"product_id":{"type":"string","ref":"products._id"},"sort":{"type":"number","default":0},"title_en":{"type":"string","required":true},"title_km":{"type":"string","required":true},"description_en":{"type":"json"},"description_km":{"type":"json"},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_deleted_at":{"type":"date"},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"users","actor":"admin","timestamps":true,"columns":{"user_id":{"type":"string","required":true,"unique":true},"name":{"type":"string","required":true},"role":{"type":"string","required":true},"email":{"type":"string","required":true,"unique":true},"actor_sheet_id":{"type":"string"},"status":{"type":"string","enum":["active","inactive"],"default":"active"},"password_hash":{"type":"string"},"profile_url":{"type":"string"},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"blocked_schedules","actor":"operation","timestamps":true,"softDelete":true,"columns":{"name":{"type":"string","required":true},"blocked_date":{"type":"date","required":true},"start_time":{"type":"string","required":true},"end_time":{"type":"string","required":true},"cleaner_ids":{"type":"string"},"associated_address":{"type":"string"},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_deleted_at":{"type":"date"},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"cleaners","actor":"operation","timestamps":true,"softDelete":true,"columns":{"name":{"type":"string","required":true},"gender":{"type":"string","required":true,"enum":["Male","Female"]},"role":{"type":"string","required":true,"enum":["LEADER","MEMBER"]},"status":{"type":"boolean","default":true},"image_url":{"type":"string"},"phone":{"type":"string"},"joined_date":{"type":"date","required":true},"auto_assign":{"type":"boolean","default":false},"expertises":{"type":"string"},"weekly_offs":{"type":"string"},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_deleted_at":{"type":"date"},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"orders","actor":"operation","timestamps":true,"columns":{"bulk_order_id":{"type":"string"},"customer_first_name":{"type":"string","required":true},"customer_last_name":{"type":"string","required":true},"customer_phone":{"type":"string","required":true},"profile_url":{"type":"string"},"category":{"type":"string","required":true},"service_type":{"type":"string","required":true},"schedule_date":{"type":"date","required":true},"duration":{"type":"number","required":true},"address":{"type":"string","required":true},"status":{"type":"string","required":true,"enum":["PENDING","ACCEPTED","IN_PROGRESS","COMPLETED","CANCELLED"],"default":"PENDING"},"payment_status":{"type":"string","enum":["PAID","UNPAID"],"default":"UNPAID"},"payment_method":{"type":"string"},"coupon_code":{"type":"string"},"amount":{"type":"number","min":0,"required":true},"service_fee":{"type":"number","min":0,"default":0},"transport_fee":{"type":"number","min":0,"default":0},"vat_fee":{"type":"number","min":0,"default":0},"discount":{"type":"number","min":0,"default":0},"net_revenue":{"type":"number","min":0,"default":0},"note":{"type":"string"},"type":{"type":"string","enum":["ORDER","DIRECT_SALE"],"default":"ORDER"},"exchange_rate":{"type":"number"},"assigned_cleaner_id":{"type":"string","ref":"cleaners._id"},"newsletter_subscription":{"type":"string","enum":["SUBSCRIBED","UNSUBSCRIBED"],"default":"UNSUBSCRIBED"},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"bcombo_transactions","actor":"finance","timestamps":true,"columns":{"transaction_id":{"type":"string","required":true,"unique":true},"customer_name":{"type":"string","required":true},"bundle_name":{"type":"string","required":true},"amount":{"type":"number","min":0,"required":true},"payment_method":{"type":"string","required":true},"status":{"type":"string","required":true,"enum":["PENDING","COMPLETED","FAILED"],"default":"PENDING"},"completed_at":{"type":"date"},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"finance_orders","actor":"finance","timestamps":true,"columns":{"order_id":{"type":"string","required":true,"ref":"orders._id"},"customer_name":{"type":"string","required":true},"customer_phone":{"type":"string","required":true},"service_category":{"type":"string","required":true},"specific_service":{"type":"string","required":true},"schedule_date":{"type":"date","required":true},"time":{"type":"string","required":true},"address":{"type":"string","required":true},"status":{"type":"string","required":true,"enum":["PENDING","ACCEPTED","IN_PROGRESS","COMPLETED","CANCELLED"]},"payment_init_date":{"type":"date"},"payment_completed_date":{"type":"date"},"payment_method":{"type":"string"},"promo_code":{"type":"string"},"original_price":{"type":"number","min":0,"required":true},"discount":{"type":"number","min":0,"default":0},"service_fee":{"type":"number","min":0,"default":0},"transport_fee":{"type":"number","min":0,"default":0},"net_revenue":{"type":"number","min":0,"default":0},"vat":{"type":"number","min":0,"default":0},"total_fee":{"type":"number","min":0,"required":true},"remark":{"type":"string"},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"topup_transactions","actor":"finance","timestamps":true,"columns":{"transaction_id":{"type":"string","required":true,"unique":true},"customer_name":{"type":"string","required":true},"customer_phone":{"type":"string"},"amount":{"type":"number","min":0,"required":true},"payment_method":{"type":"string","required":true},"status":{"type":"string","required":true,"enum":["PENDING","COMPLETED","FAILED"],"default":"PENDING"},"completed_at":{"type":"date"},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"banners","actor":"marketing","timestamps":true,"softDelete":true,"columns":{"name":{"type":"string","required":true},"title_en":{"type":"string","required":true},"type":{"type":"string","required":true,"enum":["HOME_BANNER","PRODUCT_BUNDLE","COUPON_BANNER"]},"status":{"type":"boolean","default":true},"start_date":{"type":"date","required":true},"expired_date":{"type":"date","required":true},"sort":{"type":"number","default":0},"img_url_en":{"type":"string"},"has_detail":{"type":"boolean","default":false},"has_topup":{"type":"boolean","default":false},"credit":{"type":"number"},"amount":{"type":"number"},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_deleted_at":{"type":"date"},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"coupons","actor":"marketing","timestamps":true,"softDelete":true,"columns":{"name":{"type":"string","required":true},"code":{"type":"string","required":true,"unique":true},"type":{"type":"string","required":true,"enum":["FIXED","PERCENTAGE"]},"value":{"type":"number","min":0,"required":true},"status":{"type":"boolean","default":true},"target_user":{"type":"string","enum":["ALL","SELECTED"],"default":"ALL"},"promo_text_en":{"type":"string"},"remark":{"type":"string"},"effective_date":{"type":"date"},"expired_date":{"type":"date"},"is_new_user_only":{"type":"boolean","default":false},"total_usage_limit":{"type":"number"},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_deleted_at":{"type":"date"},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"payment_links","actor":"marketing","timestamps":true,"columns":{"customer_id":{"type":"string","required":true},"customer_name":{"type":"string","required":true},"amount":{"type":"number","min":0,"required":true},"status":{"type":"string","enum":["PENDING","PAID","EXPIRED"],"default":"PENDING"},"expiry_date":{"type":"date","required":true},"paid_at":{"type":"date"},"remark":{"type":"string"},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
  {"name":"push_notifications","actor":"marketing","timestamps":true,"columns":{"name":{"type":"string","required":true},"title_en":{"type":"string","required":true},"body_en":{"type":"string","required":true},"type":{"type":"string","required":true,"enum":["GENERAL","PACKAGE_DEAL"]},"schedule_type":{"type":"string","required":true,"enum":["now","schedule","event"]},"scheduled_at":{"type":"date"},"status":{"type":"string","enum":["DRAFT","SCHEDULED","SENT","FAILED"],"default":"DRAFT"},"audience":{"type":"string","enum":["ALL","SELECTED"],"default":"ALL"},"target_user_ids":{"type":"string"},"_created_at":{"type":"date","readonly":true},"_updated_at":{"type":"date","readonly":true},"_id":{"type":"string","required":true,"unique":true,"readonly":true}}},
];

async function exportData() {
  const adapter = createSheetAdapter({
    adminSheetId: process.env.ADMIN_SHEET_ID,
    credentials: {
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
      redirectUri: process.env.GOOGLE_REDIRECT_URI,
    },
    tokens: require('./.sheet-db-tokens.json'),
  });

  adapter.registerSchemas(schemas);

  // ---------- Replace this stub with your real DB client ----------
  async function insertRow(tableName, row, userId) {
    console.log(`  INSERT INTO ${tableName}:`, JSON.stringify(row));
    // e.g. await prisma[tableName].create({ data: row });
    // userId is provided for user-sheet rows so you can associate them with the correct user FK
  }
  // ----------------------------------------------------------------

  // ─── Admin tables ───────────────────────────────────────────────────────
  const adminCtx = adapter.withContext({ userId: 'export-cli', actor: 'admin', actorSheetId: process.env.ADMIN_SHEET_ID });

  // ─── categories ───
  console.log('\nExporting table: categories...');
  try {
    const rows = await adminCtx.table('categories').findMany({});
    console.log(`  Found ${rows.length} row(s)`);
    for (const row of rows) { await insertRow('categories', row); }
    console.log(`  ✓ categories: ${rows.length} rows exported`);
  } catch (err) {
    console.error(`  ✖ categories failed:`, err.message);
  }

  // ─── category_addon_items ───
  console.log('\nExporting table: category_addon_items...');
  try {
    const rows = await adminCtx.table('category_addon_items').findMany({});
    console.log(`  Found ${rows.length} row(s)`);
    for (const row of rows) { await insertRow('category_addon_items', row); }
    console.log(`  ✓ category_addon_items: ${rows.length} rows exported`);
  } catch (err) {
    console.error(`  ✖ category_addon_items failed:`, err.message);
  }

  // ─── category_addons ───
  console.log('\nExporting table: category_addons...');
  try {
    const rows = await adminCtx.table('category_addons').findMany({});
    console.log(`  Found ${rows.length} row(s)`);
    for (const row of rows) { await insertRow('category_addons', row); }
    console.log(`  ✓ category_addons: ${rows.length} rows exported`);
  } catch (err) {
    console.error(`  ✖ category_addons failed:`, err.message);
  }

  // ─── category_category_addons ───
  console.log('\nExporting table: category_category_addons...');
  try {
    const rows = await adminCtx.table('category_category_addons').findMany({});
    console.log(`  Found ${rows.length} row(s)`);
    for (const row of rows) { await insertRow('category_category_addons', row); }
    console.log(`  ✓ category_category_addons: ${rows.length} rows exported`);
  } catch (err) {
    console.error(`  ✖ category_category_addons failed:`, err.message);
  }

  // ─── category_products ───
  console.log('\nExporting table: category_products...');
  try {
    const rows = await adminCtx.table('category_products').findMany({});
    console.log(`  Found ${rows.length} row(s)`);
    for (const row of rows) { await insertRow('category_products', row); }
    console.log(`  ✓ category_products: ${rows.length} rows exported`);
  } catch (err) {
    console.error(`  ✖ category_products failed:`, err.message);
  }

  // ─── credentials ───
  console.log('\nExporting table: credentials...');
  try {
    const rows = await adminCtx.table('credentials').findMany({});
    console.log(`  Found ${rows.length} row(s)`);
    for (const row of rows) { await insertRow('credentials', row); }
    console.log(`  ✓ credentials: ${rows.length} rows exported`);
  } catch (err) {
    console.error(`  ✖ credentials failed:`, err.message);
  }

  // ─── items ───
  console.log('\nExporting table: items...');
  try {
    const rows = await adminCtx.table('items').findMany({});
    console.log(`  Found ${rows.length} row(s)`);
    for (const row of rows) { await insertRow('items', row); }
    console.log(`  ✓ items: ${rows.length} rows exported`);
  } catch (err) {
    console.error(`  ✖ items failed:`, err.message);
  }

  // ─── permissions ───
  console.log('\nExporting table: permissions...');
  try {
    const rows = await adminCtx.table('permissions').findMany({});
    console.log(`  Found ${rows.length} row(s)`);
    for (const row of rows) { await insertRow('permissions', row); }
    console.log(`  ✓ permissions: ${rows.length} rows exported`);
  } catch (err) {
    console.error(`  ✖ permissions failed:`, err.message);
  }

  // ─── popular_service_items ───
  console.log('\nExporting table: popular_service_items...');
  try {
    const rows = await adminCtx.table('popular_service_items').findMany({});
    console.log(`  Found ${rows.length} row(s)`);
    for (const row of rows) { await insertRow('popular_service_items', row); }
    console.log(`  ✓ popular_service_items: ${rows.length} rows exported`);
  } catch (err) {
    console.error(`  ✖ popular_service_items failed:`, err.message);
  }

  // ─── popular_services ───
  console.log('\nExporting table: popular_services...');
  try {
    const rows = await adminCtx.table('popular_services').findMany({});
    console.log(`  Found ${rows.length} row(s)`);
    for (const row of rows) { await insertRow('popular_services', row); }
    console.log(`  ✓ popular_services: ${rows.length} rows exported`);
  } catch (err) {
    console.error(`  ✖ popular_services failed:`, err.message);
  }

  // ─── product_options ───
  console.log('\nExporting table: product_options...');
  try {
    const rows = await adminCtx.table('product_options').findMany({});
    console.log(`  Found ${rows.length} row(s)`);
    for (const row of rows) { await insertRow('product_options', row); }
    console.log(`  ✓ product_options: ${rows.length} rows exported`);
  } catch (err) {
    console.error(`  ✖ product_options failed:`, err.message);
  }

  // ─── products ───
  console.log('\nExporting table: products...');
  try {
    const rows = await adminCtx.table('products').findMany({});
    console.log(`  Found ${rows.length} row(s)`);
    for (const row of rows) { await insertRow('products', row); }
    console.log(`  ✓ products: ${rows.length} rows exported`);
  } catch (err) {
    console.error(`  ✖ products failed:`, err.message);
  }

  // ─── role_permissions ───
  console.log('\nExporting table: role_permissions...');
  try {
    const rows = await adminCtx.table('role_permissions').findMany({});
    console.log(`  Found ${rows.length} row(s)`);
    for (const row of rows) { await insertRow('role_permissions', row); }
    console.log(`  ✓ role_permissions: ${rows.length} rows exported`);
  } catch (err) {
    console.error(`  ✖ role_permissions failed:`, err.message);
  }

  // ─── roles ───
  console.log('\nExporting table: roles...');
  try {
    const rows = await adminCtx.table('roles').findMany({});
    console.log(`  Found ${rows.length} row(s)`);
    for (const row of rows) { await insertRow('roles', row); }
    console.log(`  ✓ roles: ${rows.length} rows exported`);
  } catch (err) {
    console.error(`  ✖ roles failed:`, err.message);
  }

  // ─── schema_versions ───
  console.log('\nExporting table: schema_versions...');
  try {
    const rows = await adminCtx.table('schema_versions').findMany({});
    console.log(`  Found ${rows.length} row(s)`);
    for (const row of rows) { await insertRow('schema_versions', row); }
    console.log(`  ✓ schema_versions: ${rows.length} rows exported`);
  } catch (err) {
    console.error(`  ✖ schema_versions failed:`, err.message);
  }

  // ─── task_info ───
  console.log('\nExporting table: task_info...');
  try {
    const rows = await adminCtx.table('task_info').findMany({});
    console.log(`  Found ${rows.length} row(s)`);
    for (const row of rows) { await insertRow('task_info', row); }
    console.log(`  ✓ task_info: ${rows.length} rows exported`);
  } catch (err) {
    console.error(`  ✖ task_info failed:`, err.message);
  }

  // ─── users ───
  console.log('\nExporting table: users...');
  try {
    const rows = await adminCtx.table('users').findMany({});
    console.log(`  Found ${rows.length} row(s)`);
    for (const row of rows) { await insertRow('users', row); }
    console.log(`  ✓ users: ${rows.length} rows exported`);
  } catch (err) {
    console.error(`  ✖ users failed:`, err.message);
  }

  // Tip: run `sheet-db export-data --all-users` to also export all registered user sheets

  console.log('\nData export complete.');
}

exportData().catch(console.error);
