const BANNER_CAMPAIGN_BODY_TEMPLATE = {
  en: '<h2>🎉 bEasy Khmer New Year Campaign 🎉</h2><div><span class="strong">Get 20% off when you book services with bEasy!</span></div><h3>🎁 How to apply coupon (KNY20)</h3><ul><li>Download the bEasy app</li><li>Register an account</li><li>Book general or deep cleaning service</li><li>Enter promo code <span class="strong">KNY20</span> and apply 💸</li></ul><h3>🛠 Available Services</h3><ul><li>General cleaning</li><li>Deep cleaning</li></ul><h3>📅 Campaign Period</h3><div>From now until <span class="strong">April 19, 2026</span></div><hr><div>📲 <span class="strong">Don’t miss your lucky chance!</span><br>Start using bEasy today — easy, fast, and reliable!</div>',
  km: '<h2>🎉 bEasy Khmer New Year Campaign 🎉</h2><div><span class="strong">Get 20% off when you book services with bEasy!</span></div><h3>🎁 How to apply coupon (KNY20)</h3><ul><li>Download the bEasy app</li><li>Register an account</li><li>Book general or deep cleaning service</li><li>Enter promo code <span class="strong">KNY20</span> and apply 💸</li></ul><h3>🛠 Available Services</h3><ul><li>General cleaning</li><li>Deep cleaning</li></ul><h3>📅 Campaign Period</h3><div>From now until <span class="strong">April 19, 2026</span></div><hr><div>📲 <span class="strong">Don’t miss your lucky chance!</span><br>Start using bEasy today — easy, fast, and reliable!</div>',
  vi: '<h2>🎉 bEasy Khmer New Year Campaign 🎉</h2><div><span class="strong">Get 20% off when you book services with bEasy!</span></div><h3>🎁 How to apply coupon (KNY20)</h3><ul><li>Download the bEasy app</li><li>Register an account</li><li>Book general or deep cleaning service</li><li>Enter promo code <span class="strong">KNY20</span> and apply 💸</li></ul><h3>🛠 Available Services</h3><ul><li>General cleaning</li><li>Deep cleaning</li></ul><h3>📅 Campaign Period</h3><div>From now until <span class="strong">April 19, 2026</span></div><hr><div>📲 <span class="strong">Don’t miss your lucky chance!</span><br>Start using bEasy today — easy, fast, and reliable!</div>',
  tw: '<h2>🎉 bEasy Khmer New Year Campaign 🎉</h2><div><span class="strong">Get 20% off when you book services with bEasy!</span></div><h3>🎁 How to apply coupon (KNY20)</h3><ul><li>Download the bEasy app</li><li>Register an account</li><li>Book general or deep cleaning service</li><li>Enter promo code <span class="strong">KNY20</span> and apply 💸</li></ul><h3>🛠 Available Services</h3><ul><li>General cleaning</li><li>Deep cleaning</li></ul><h3>📅 Campaign Period</h3><div>From now until <span class="strong">April 19, 2026</span></div><hr><div>📲 <span class="strong">Don’t miss your lucky chance!</span><br>Start using bEasy today — easy, fast, and reliable!</div>',
  cn: '<h2>🎉 bEasy Khmer New Year Campaign 🎉</h2><div><span class="strong">Get 20% off when you book services with bEasy!</span></div><h3>🎁 How to apply coupon (KNY20)</h3><ul><li>Download the bEasy app</li><li>Register an account</li><li>Book general or deep cleaning service</li><li>Enter promo code <span class="strong">KNY20</span> and apply 💸</li></ul><h3>🛠 Available Services</h3><ul><li>General cleaning</li><li>Deep cleaning</li></ul><h3>📅 Campaign Period</h3><div>From now until <span class="strong">April 19, 2026</span></div><hr><div>📲 <span class="strong">Don’t miss your lucky chance!</span><br>Start using bEasy today — easy, fast, and reliable!</div>'
} as const;

export const replaceContent = BANNER_CAMPAIGN_BODY_TEMPLATE;
