export const ACTIONS = {
  VIEW: 'VIEW',
  ADD: 'ADD',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  EXPORT: 'EXPORT',
  ASSIGN: 'ASSIGN'
};

export const MODULES = {
  DASHBOARD: 'DASHBOARD',
  ORDER: 'ORDER',
  FINANCE_ORDER: 'FINANCE-ORDER',
  FINANCE_TOPUP: 'FINANCE-TOPUP',
  FINANCE_BCOMBO: 'FINANCE-BCOMBO',
  FINANCE_DIRECT_SALES: 'FINANCE-DIRECT_SALES',
  CLEANER: 'CLEANER',
  MARKETING_CUSTOMER: 'MARKETING-CUSTOMER',
  MARKETING_COUPON: 'MARKETING-COUPON',
  MARKETING_PAYMENT_LINK: 'MARKETING-PAYMENT_LINK',
  MARKETING_OTP: 'MARKETING-OTP',
  MARKETING_NOTIFICATION: 'MARKETING-NOTIFICATION',
  SETUP_ITEM: 'SETUP-ITEM',
  SETUP_SCHEDULE: 'SETUP-SCHEDULE',
  MARKETING_OVERVIEW: 'MARKETING-OVERVIEW',
  MARKETING_BANNER: 'MARKETING-BANNER',
  EXCHANGE_RATE: 'EXCHANGE-RATE',
  ACTIVITY_LOG: 'ACTIVITY_LOG'
};
