export const mockBanners: BannerProps[] = [
  {
    id: 1,
    name: 'Summer Promo',
    type: 'HOME-BANNER',
    status: true,
    sort: 1,
    titleEn: 'Summer Special Offer',
    titleKm: 'ការផ្តល់ជូនពិសេសសម្រាប់រដូវក្តៅ',
    titleTw: '夏季特別優惠',
    titleCn: '夏季特别优惠',
    titleVi: 'Ưu đãi đặc biệt mùa hè',
    imgUrlEn: 'https://placehold.co/600x200?text=Summer+Banner+EN',
    imgUrlKm: 'https://placehold.co/600x200?text=Summer+Banner+KM',
    imgUrlVi: 'https://placehold.co/600x200?text=Summer+Banner+VI',
    imgUrlCn: 'https://placehold.co/600x200?text=Summer+Banner+CN',
    imgUrlTw: 'https://placehold.co/600x200?text=Summer+Banner+TW',
    imgDetailUrlEn: null,
    imgDetailUrlKm: null,
    imgDetailUrlVi: null,
    imgDetailUrlCn: null,
    imgDetailUrlTw: null,
    hasDetail: false,
    hasTopup: false,
    hasBooking: false,
    contentEn: null,
    contentKm: null,
    contentVi: null,
    contentTw: null,
    contentCn: null,
    deeplink: null,
    deeplinkType: '',
    amount: 0,
    credit: 0,
    startDate: '2026-05-01',
    expiredDate: '2026-08-31',
    createdAt: '2026-04-01T00:00:00.000Z',
    updatedAt: '2026-04-01T00:00:00.000Z',
    unsupportedCoupons: []
  },
  {
    id: 2,
    name: 'New Year Bundle',
    type: 'PRODUCT-BUNDLE',
    status: true,
    sort: 2,
    titleEn: 'New Year Bundle Deal',
    titleKm: 'កញ្ចប់ឆ្នាំថ្មី',
    titleTw: '新年套裝優惠',
    titleCn: '新年套餐优惠',
    titleVi: 'Gói ưu đãi năm mới',
    imgUrlEn: 'https://placehold.co/600x200?text=Bundle+EN',
    imgUrlKm: 'https://placehold.co/600x200?text=Bundle+KM',
    imgUrlVi: 'https://placehold.co/600x200?text=Bundle+VI',
    imgUrlCn: 'https://placehold.co/600x200?text=Bundle+CN',
    imgUrlTw: 'https://placehold.co/600x200?text=Bundle+TW',
    imgDetailUrlEn: null,
    imgDetailUrlKm: null,
    imgDetailUrlVi: null,
    imgDetailUrlCn: null,
    imgDetailUrlTw: null,
    hasDetail: false,
    hasTopup: false,
    hasBooking: false,
    contentEn: null,
    contentKm: null,
    contentVi: null,
    contentTw: null,
    contentCn: null,
    deeplink: null,
    deeplinkType: '',
    amount: 0,
    credit: 0,
    startDate: null,
    expiredDate: null,
    createdAt: '2026-04-15T00:00:00.000Z',
    updatedAt: '2026-04-15T00:00:00.000Z',
    unsupportedCoupons: []
  },
  {
    id: 3,
    name: 'Referral Coupon',
    type: 'COUPON-BANNER',
    status: false,
    sort: 3,
    titleEn: 'Invite Friends & Earn',
    titleKm: 'អញ្ជើញមិត្តភ័ក្ដិ',
    titleTw: '邀請朋友並賺取獎勵',
    titleCn: '邀请朋友并赚取奖励',
    titleVi: 'Mời bạn bè và nhận thưởng',
    imgUrlEn: 'https://placehold.co/600x200?text=Coupon+EN',
    imgUrlKm: 'https://placehold.co/600x200?text=Coupon+KM',
    imgUrlVi: 'https://placehold.co/600x200?text=Coupon+VI',
    imgUrlCn: 'https://placehold.co/600x200?text=Coupon+CN',
    imgUrlTw: 'https://placehold.co/600x200?text=Coupon+TW',
    imgDetailUrlEn: null,
    imgDetailUrlKm: null,
    imgDetailUrlVi: null,
    imgDetailUrlCn: null,
    imgDetailUrlTw: null,
    hasDetail: false,
    hasTopup: false,
    hasBooking: false,
    contentEn: null,
    contentKm: null,
    contentVi: null,
    contentTw: null,
    contentCn: null,
    deeplink: null,
    deeplinkType: '',
    amount: 0,
    credit: 0,
    startDate: null,
    expiredDate: '2026-06-30',
    createdAt: '2026-04-20T00:00:00.000Z',
    updatedAt: '2026-04-20T00:00:00.000Z',
    unsupportedCoupons: []
  }
];
