export const mockProductOptions: ProductOptionAttributes[] = [
  {
    id: 1,
    nameEn: '2 Cleaners - 3 Hours',
    nameKm: 'អ្នកសំអាត ២នាក់ - ៣ម៉ោង',
    nameVi: '2 người dọn - 3 giờ',
    nameCn: '2名清洁工 - 3小时',
    nameTw: '2名清潔工 - 3小時',
    imgUrl: null,
    duration: '3',
    qty: 1,
    status: true,
    amount: 30,
    floorCount: '0',
    bedroomCount: '0',
    hourCount: '3',
    type: 'CLEANER',
    cleanerCount: '2',
    count: 1,
    infoEn: null,
    infoKm: null,
    infoVi: null,
    infoCn: null,
    infoTw: null,
    remarkEn: null,
    remarkZh: null,
    remarkCh: null,
    remarkVi: null,
    remarkKh: null,
    product: { id: 1, nameEn: 'Standard Cleaning' }
  },
  {
    id: 2,
    nameEn: '3 Cleaners - 4 Hours',
    nameKm: 'អ្នកសំអាត ៣នាក់ - ៤ម៉ោង',
    nameVi: '3 người dọn - 4 giờ',
    nameCn: '3名清洁工 - 4小时',
    nameTw: '3名清潔工 - 4小時',
    imgUrl: null,
    duration: '4',
    qty: 1,
    status: true,
    amount: 45,
    floorCount: '0',
    bedroomCount: '0',
    hourCount: '4',
    type: 'CLEANER',
    cleanerCount: '3',
    count: 1,
    infoEn: null,
    infoKm: null,
    infoVi: null,
    infoCn: null,
    infoTw: null,
    remarkEn: null,
    remarkZh: null,
    remarkCh: null,
    remarkVi: null,
    remarkKh: null,
    product: { id: 1, nameEn: 'Standard Cleaning' }
  },
  {
    id: 3,
    nameEn: '1 Technician - 2 Hours',
    nameKm: 'បច្ចេកទេស ១នាក់ - ២ម៉ោង',
    nameVi: '1 kỹ thuật viên - 2 giờ',
    nameCn: '1名技术员 - 2小时',
    nameTw: '1名技術員 - 2小時',
    imgUrl: null,
    duration: '2',
    qty: 1,
    status: true,
    amount: 80,
    floorCount: '0',
    bedroomCount: '0',
    hourCount: '2',
    type: 'TECHNICIAN',
    cleanerCount: '0',
    count: 1,
    infoEn: null,
    infoKm: null,
    infoVi: null,
    infoCn: null,
    infoTw: null,
    remarkEn: null,
    remarkZh: null,
    remarkCh: null,
    remarkVi: null,
    remarkKh: null,
    product: { id: 3, nameEn: 'Pest Control Service' }
  }
];
