export const mockProducts: ProductAttributes[] = [
  {
    id: 1,
    iconUrl: 'https://placehold.co/64x64?text=Std',
    nameEn: 'Standard Cleaning',
    nameKm: 'សំអាតស្តង់ដារ',
    nameVi: 'Dọn dẹp tiêu chuẩn',
    nameCn: '标准清洁',
    nameTw: '標準清潔',
    status: true,
    amount: 25,
    sort: 1,
    taskInfoEn: [{ key: 'Includes', value: ['Dusting', 'Vacuuming', 'Mopping'] }],
    taskInfoKm: null,
    taskInfoCn: null,
    taskInfoTw: null,
    taskInfoVi: null,
    category: { id: 1, nameEn: 'Home Cleaning' },
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-04-01T00:00:00.000Z'
  },
  {
    id: 2,
    iconUrl: 'https://placehold.co/64x64?text=Deep',
    nameEn: 'Deep Cleaning',
    nameKm: 'សំអាតស៊ីជម្រៅ',
    nameVi: 'Dọn dẹp sâu',
    nameCn: '深度清洁',
    nameTw: '深度清潔',
    status: true,
    amount: 50,
    sort: 2,
    taskInfoEn: [{ key: 'Includes', value: ['Bathroom scrub', 'Kitchen deep clean', 'Window cleaning'] }],
    taskInfoKm: null,
    taskInfoCn: null,
    taskInfoTw: null,
    taskInfoVi: null,
    category: { id: 1, nameEn: 'Home Cleaning' },
    createdAt: '2026-01-15T00:00:00.000Z',
    updatedAt: '2026-04-01T00:00:00.000Z'
  },
  {
    id: 3,
    iconUrl: 'https://placehold.co/64x64?text=Pest',
    nameEn: 'Pest Control Service',
    nameKm: 'សេវាបង្ក្រាបសត្វល្អិត',
    nameVi: 'Dịch vụ kiểm soát côn trùng',
    nameCn: '害虫控制服务',
    nameTw: '害蟲控制服務',
    status: false,
    amount: 80,
    sort: 3,
    taskInfoEn: null,
    taskInfoKm: null,
    taskInfoCn: null,
    taskInfoTw: null,
    taskInfoVi: null,
    category: { id: 2, nameEn: 'Pest Control' },
    createdAt: '2026-02-01T00:00:00.000Z',
    updatedAt: '2026-04-10T00:00:00.000Z'
  }
];
